language: c

matrix:
  fast_finish: true
  include:

    - name: x32 test
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - make -C tests test MOREFLAGS=-mx32
